---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-stock-service-edb-com-v1-stockreport
  failurePolicy: Fail
  name: mstockreport.kb.io
  rules:
  - apiGroups:
    - stock-service.edb.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stockreports
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-stock-service-edb-com-v1-stockreport
  failurePolicy: Fail
  name: vstockreport.kb.io
  rules:
  - apiGroups:
    - stock-service.edb.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stockreports
  sideEffects: None
