---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - configmaps/status
  verbs:
  - get
- apiGroups:
  - stock-service.edb.com
  resources:
  - stockreports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stock-service.edb.com
  resources:
  - stockreports/finalizers
  verbs:
  - update
- apiGroups:
  - stock-service.edb.com
  resources:
  - stockreports/status
  verbs:
  - get
  - patch
  - update
